### ISSUE TITLE
Move creation of confetti off main thread

### ISSUE THREAD

**Issue by fatuhoku** [life360/confetti#9]
There's a noticeable lag even on iPad Air (and the iPad 2, most definitely!) when creating just over 40 confetti pieces. That's not very impressive :/ :(  Animating that number seems to be no problem.

How about moving some of the initialization code off the main thread?

**Comment by foffux** [comment]
Hello
Could you please clarify this issue? Because it seemed very important for my opinion.
@fatuhoku: didn't you do any pull request for that?
@mmislam101: why this issue has been closed?

Thank you.

**Comment by mmislam101** [comment]
The last 5 commits on the main branch (and release version 1.1.3) resolves this issue. The issue was that if you used a confetti count of 40, it would take a really long time for the confetti to be displayed.

There is still some lag but it's not as terrible. Any further optimizations, you guys will have to help me out with. Thanks!

**Comment by foffux** [comment]
Thanks for clarification 
I will try with more than 20 confetti like I am doing right now then. I am doing also a for loop of 4: hope it is not too heavy...

Inviato da iPhone

**Comment by mmislam101** [comment]
Yah. Please let us know how it turns out for you.
